### ISSUE TITLE
osx screen mirror stream width & height issue (rpi4)

### ISSUE THREAD

**Issue by dmtth** [FD-/RPiPlay#11]
Hi, GREAT WORK there!
Although is it normal that i try to stream a 1080p picture (or larger) from osx, the debug said:
width_source = 1804
height_source = 1016
width = 1804
height = 1016

even if i try with 720p:
width_source = 1280
height_source = 720
width = 1804
height = 1016

Thanks in advance!
Cheers

**Comment by lightxxx** [comment]
Use https://apps.apple.com/app/easyres/id688211836?ls=1&mt=12

**Comment by FD-** [comment]
The values you see are just what the source (macOS) tells RPiPlay about the stream. AFAICT, RPiPlay correctly advertises to the macOS client as a 1080p screen, so I don't think there's anything RPiPlay could change here.
