### ISSUE TITLE
Apple TV - "The connected display is not authorised to play protected films"

### ISSUE THREAD

**Issue by VictorEscalona** [FD-/RPiPlay#114]
Unfortunately when I tried to watch something in Apple TV and mirror it to the TV we get this error "**Cannot Play Film** The connected display is not authorised to play protected films"

Im assuming this is not an actual issue and more to do with Apple's way to protect pirating. I wonder if theres a way to allow this to be a authorised display.

P.S. Great job at creating and improving this! Works brilliantly for anything else.

**Comment by FD-** [comment]
Assuming the affected apps allow mirroring to a genuine Apple TV, I suspect this is related to the version of the AirPlay mirroring protocol RPiPlay implements. Newer versions seem to use some kind of additional encryption.
