### ISSUE TITLE
Raspberry pi zero w

### ISSUE THREAD

**Issue by xRealNeon** [FD-/RPiPlay#119]
Hello I just wanted to ask if everything works smoothly on the raspberry pi zero w?
Because the readme says that this is the goal.

**Comment by FD-** [comment]
Also in the Readme: "Both audio and video work fine on a Raspberry Pi 3B+ and a Raspberry Pi Zero, though playback is a bit smoother on the 3B+." From my experience, if you don't run anything else on the Pi Zero (at the same time), then RPiPlay audio and video work fine.

**Comment by xRealNeon** [comment]
Ok thank you
