### ISSUE TITLE
Clarify in the docs: which Raspbian image

### ISSUE THREAD

**Issue by frnhr** [FD-/RPiPlay#134]
Sorry, "Raspberry Pi OS" 😒 

I'm not sure if I should use the Lite version (without X system) or the standard version.

**Comment by jannisjr** [comment]
It didn't work for me with Lite, I had to use the full version

**Comment by FD-** [comment]
I've been mostly using it on Raspbian (now Raspberry Pi OS) **_Lite_**, so it definitely does work there as well.

**Comment by frnhr** [comment]
@FD- thanks for the clarification! I have added a line to the README: https://github.com/FD-/RPiPlay/pull/173
