### ISSUE TITLE
Configure Audio

### ISSUE THREAD

**Issue by kamikaze463** [FD-/RPiPlay#135]
I could be sounding really stupid but I have one question, How do I route audio to 3.5mm jack instead of HDMI. Currently the audio output is just fine with HDMI.

**Comment by flatsiedatsie** [comment]
I have the same question.

**Comment by flatsiedatsie** [comment]
are you running it with `-a analog`?

**Comment by kamikaze463** [comment]
Yes. I’m   
  
  
  

  

  

    

  
  
  
  

  
  
>

**Comment by flatsiedatsie** [comment]
Have you tried `amixer cset numid=3 1` ?

**Comment by kamikaze463** [comment]
it throws an error 
"amixer: Cannot find the given element from control default"

`amixer` gives me below output:

_Simple mixer control 'HDMI',0
  Capabilities: pvolume pvolume-joined pswitch pswitch-joined
  Playback channels: Mono
  Limits: Playback -10239 - 400
  Mono: Playback 400 [100%] [4.00dB] [on]_

However, I've set the playback to headphones in raspiconfig

**Comment by FD-** [comment]
Since RPiPlay uses OpenMAX for audio, not ALSA, amixer won't help here, I'm afraid. The -a analog switch should work though (it does for me on Pi Zero and 3B+) !

**Comment by kamikaze463** [comment]
Well, something happened but the issue seem to be fixed since yesterday's apt upgrade. Not sure if something in that update fixed my issue.

**Comment by pallas** [comment]
Seems resolved, closing. Please lmk if that's incorrect.
