### ISSUE TITLE
aacDecoder_DecodeFrame error

### ISSUE THREAD

**Issue by flatsiedatsie** [FD-/RPiPlay#137]
From reading the issue queue I know this isn't an error, but a lack of implementation. But I thought I'd mention it anyway, as many users may be searching based on this error.

This happens when I try to use only audio casting (and not display mirroring), for example when I just want to stream some music to the Raspberry Pi 4. From what I've read, supporting audio only casting is currently not what RpiPlay should be used for. Use Shairport-Sync for that.

The good news is that Shairport Sync and RPiPlay seem fine with running alongside eachother. Another upshot is that if you want to only stream audio, the second display isn't also set to mirror the desktop.

My only issue is that it can lead to a lot of misunderstanding with end users. When they want to stream audio, they will currently see both an `RPiPLay` and `Shairport` option in the dropdown.

Would it perhaps be easy to avoid MacOS showing RPiPlay as an audio-only output option in that dropdown? Then if both pieces of software were given the same display name, users might not even realize they're connecting to two different pieces of software.

**Comment by flatsiedatsie** [comment]
I just tried to comment out the line `dnssd_register_raop(dnssd, port)` in rpiplay.cc, but that didn't do it.

Maybe there are other places I should comment it out. It's mentioned in `dsnsd.c` and `dnssd.h` too. I commented out the entire function in the first, and the reference in the latter.

It still shows up as 'RpiPlay'. Very tenacious!

**Comment by FD-** [comment]
Could be because a genuine Mirroring-only device doesn't exist. All official Apple products that support Mirroring also implement the other AirPlay subprotocols (audio, video, etc).

**Comment by flatsiedatsie** [comment]
Yes that's what I was starting to suspect too.

**Comment by pallas** [comment]
Was the actual trace ever posted?

**Comment by pallas** [comment]
Sorry, did not mean to close.

**Comment by pallas** [comment]
I am bad at clicking, apparently.

**Comment by flatsiedatsie** [comment]
What do you mean by 'trace'?

**Comment by pallas** [comment]
I have a commit at https://github.com/pallas/RPiPlay/commit/f4ef14cc63d2d5ef89127ab63ac08d3cf120bad1 that bumps to a newer-but-not-released version of FDK-AAC.

**Comment by pallas** [comment]
stale, & we're tracking upstream
