### ISSUE TITLE
Audio/video cutting out on RPI 4 - 4GB 

### ISSUE THREAD

**Issue by HardBamboo** [FD-/RPiPlay#140]
When first starting a video the audio works fine, but if there is ever a point of no audio output the audio cuts out and stops working completely. The audio output is set to hdmi using the -a flag and is connected to the HDMI0 port.
LOG: [log.txt](https://github.com/FD-/RPiPlay/files/4908301/log.txt)

**Comment by FD-** [comment]
Have you tried low latency mode?

**Comment by HardBamboo** [comment]
> Have you tried low latency mode?

-l has seemed to fix it, I realized the video was cutting out because the PI was falling asleep. Maybe add that in the readme? cheers!
