### ISSUE TITLE
Docker builder

### ISSUE THREAD

**Issue by nicolaspernoud** [FD-/RPiPlay#150]
Hello,

Thanks for this amazing work.
For your information, I made a script that build RPiPlay with docker and enable it to be used directly in LibreELEC (by getting the libdns_sd.so.1 library locally). Feel free to include it in your repo or point to it in your readme...

The script is here : https://github.com/nicolaspernoud/RPiPlay-docker-builder .

Best regards.

**Comment by pallas** [comment]
Thanks, this is great. If you want to include it in mainline, can you please make a PR?

**Comment by jhfdevelop** [comment]
Hey,
thank you everyone for your great work.
I attempted to containerize the app for the raspberry pi using your docker builder @nicolaspernoud.

Feel free to have a look: https://github.com/jhfdevelop/rpiplay_docker

**Comment by nicolaspernoud** [comment]
@jhfdevelop : I had a look, nice !
@pallas : PR still pending...
