### ISSUE TITLE
build: Cannot determine link language for target "ilclient"

### ISSUE THREAD

**Issue by retani** [FD-/RPiPlay#16]
First: Great project!

Second: you also need: 
`sudo apt-get install build-essential`

Third:
I am stuck with 
```
CMake Error: Cannot determine link language for target "ilclient".
CMake Error: CMake can not determine linker language for target: ilclient
```

... and subsequently
`make[2]: *** No rule to make target 'renderers/CMakeFiles/ilclient.dir/build'.  Stop.`

I am trying to compile on a raspberry with OSMC. What can I do to make it happen?

**Comment by FD-** [comment]
Duplicate of issue #10
