### ISSUE TITLE
network connection not possible

### ISSUE THREAD

**Issue by muetzel** [FD-/RPiPlay#161]
Hi!
I installed RPiPlay on Raspi 3. After starting I can see the raspi on my phone. It says "connected" for a short time, tut then it tells me, connection not possible. Network not ready.
Both are on the same wifi. Should work.
As I don't have an IOS Device, I simulate it by using AirServer. So this could be a problem. But my colleague could't connect with her IPhone either.
btw: I start RPIPlay like that: 
'pi@raspberrypi: ~/RPiPlay/build & ./rpiplay`

**Comment by pallas** [comment]
This is not enough information to debug an issue.
