### ISSUE TITLE
Connected and working, but windowed, not fullscreen

### ISSUE THREAD

**Issue by ema07cqc** [FD-/RPiPlay#162]
Hello there, this is a great project.
Got it working on Ubuntu 20.04 but its windowed mode. There is a way to get it fullscreen? Thanks,

**Comment by rajb245** [comment]
@ema07cqc can you share more about how you got it working on Ubuntu? I used apt to install all the pre-requisites, was able to cmake and make, and call it like this: `./rpiplay -n "Laptop" -d`
I can see an AirPlay device called "Laptop" on my iPhone and it connects. I can even hear the audio come across the connection! But I don't see any video. Does rpiplay open a new window for the video automatically when it starts, or when something connects?

**Comment by ema07cqc** [comment]
> @ema07cqc can you share more about how you got it working on Ubuntu? I used apt to install all the pre-requisites, was able to cmake and make, and call it like this: `./rpiplay -n "Laptop" -d`
> I can see an AirPlay device called "Laptop" on my iPhone and it connects. I can even hear the audio come across the connection! But I don't see any video. Does rpiplay open a new window for the video automatically when it starts, or when something connects?

Hi there. I tried mirroring my MacBook 12" with Catalina 10.15.7.
Your command seems ok. Im using "/RPiPlay/build/./rpiplay -l -a off -b off" because i don't need audio.
It opens a new window titled "unknown" and I can o minimize or resize only.

**Comment by RafaelGreenblatt** [comment]
I was able to do this by setting a shortcut for "toggle fullscreen mode" in the "keyboard" section of system settings.  AFAICT this is an all-purpose solution (i.e. nothing to do specifically with this project).

**Comment by pallas** [comment]
Those instructions are helpful. Since it's general and it sounds like it works, going to close this issue.

**Comment by tanmaster** [comment]
> I was able to do this by setting a shortcut for "toggle fullscreen mode" in the "keyboard" section of system settings. AFAICT this is an all-purpose solution (i.e. nothing to do specifically with this project).

this worked for me as well
