### ISSUE TITLE
Can not make

### ISSUE THREAD

**Issue by Deymon112** [FD-/RPiPlay#17]
![Безымянный](https://user-images.githubusercontent.com/17392268/64913839-567e8b00-d750-11e9-9588-d1826feef4fe.jpg)
Invalid format libbrcmglesv2.so . Help please. Try it on raspberry (raspbian) and ubuntu 18.04 on my PC.

**Comment by FD-** [comment]
Does /opt/vc/lib/libbrcmGLESv2.so exist? On Ubuntu, it likely doesn't. On Raspbian, it should.

**Comment by Deymon112** [comment]
Yes. I download it. I thought a problem with rights, set 777. It did not help

**Comment by FD-** [comment]
What does that mean, you downloaded it? Where from? What OS are you running?

**Comment by Deymon112** [comment]
https://github.com/FD-/RPiPlay/issues/10#issuecomment-521695708
From this post.
Raspbian stretch, Ubuntu 18.04

**Comment by FD-** [comment]
On Stretch, the files are already present, so you shouldn't see the issue there unless you modified the system. In the comment linked above, I was referring to the ilclient library sources, which are then freshly compiled during RPiPlay's build. libbrcmglesv2.so is a pre-built static library, so it's likely not portable.

What exactly does your error message say (translated to English)?

**Comment by Deymon112** [comment]
/opt/vc/lib/libbrcmGLESc2.so: error adding symbols: wrong file format
collect2: error: Id returned 1 exit status
CMakeFiles/rpiplay.dir/build.make:110: recipe execution error for purposes "rpiplay"
Make [2]: *** [rpiplay] Error 1
CMakeFiles/Makefile2:75: recipe execution error for purposes "CMakeFiles/rpiplay.dir/all"
make[1]: *** [CMakeFiles/rpiplay.dir/all] Error2
Makefile:83: recipe execution error for purposes "all"
make: *** [all[ Error2

**Comment by FD-** [comment]
What Raspberry Pi model are you using?

**Comment by Deymon112** [comment]
Virtualbox with raspbian

**Comment by Deymon112** [comment]
I want to test it on my pc then buy raspberry

**Comment by FD-** [comment]
That is the problem then. You're likely running this on an x86 CPU (most laptops or desktop computers) and the Raspberry Pi is an ARM CPU, so you cannot just copy binaries compiled for the Raspberry Pi to your computer and expect them to work.
Even if VirtualBox would emulate the ARM instruction set, the Broadcom VideoCore GPU cannot be emulated, and RPiPlay makes use of it for rendering.

**Comment by Deymon112** [comment]
Oh... Sorry. Thanks for help. 
What model do you recommend for stable work?

**Comment by FD-** [comment]
I only tested on a Pi Zero and a Pi 3B+, and of these two, the 3B+ performs better.
