### ISSUE TITLE
Vide Casting not working yet ?

### ISSUE THREAD

**Issue by moda20** [FD-/RPiPlay#171]
I installed RpiPlay on my libreelec using the dockerBuilder in the pull request #168 
but I couldn't cast videos from QuickTime or youtube. on youtube the cast button is not there, and quicktime doesn't find the server I am running. Yet I can still mirror my screen and I can find my server from the display icon.

**Comment by FD-** [comment]
Not implemented, but you‘re welcome to contribute.
