### ISSUE TITLE
Audio Output to DAC

### ISSUE THREAD

**Issue by DaCapitalist** [FD-/RPiPlay#174]
Hi Guys,

I am thinking about adding an Audio DAC to my Raspberry Pi Zero (Allo Miniboss or Hifiberry dac+).

Will it be possible to output the audio to the DAC both of these DACs? And if yes, are there specific setting to set to switch the audio output from hdmi to DAC? Is one of the 2 devices favourable in terms of audio quality or ease to setup with RPiPlay?

Many thanks

**Comment by petitxef** [comment]
I have a pHat DAC on my rpi zero W and works fine, but NO sound (I open a ticket)

**Comment by FD-** [comment]
DACs are not currently supported by RPiPlay on Raspberry Pi, at least not with the default OpenMAX renderers. See #33.
