### ISSUE TITLE
what's the networking port for RPiPlay?

### ISSUE THREAD

**Issue by meadlai** [FD-/RPiPlay#175]
Hello,

I build and start RPiPlay in the Pi 4B+, but no response in the bash shell, so I suspect the firewall block it, can anyone tell me the port for airplay service? thank you.
```bash
sudo apt-get  install ufw
sudo ufw enable
sudo ufw default deny
sudo ufw allow 8080
sudo ufw allow 22
sudo ufw reload
```

**Comment by pallas** [comment]
The port is ephemeral, and advertised by mDNS. It should be possible to edit the code to bind to a specific port.

**Comment by pallas** [comment]
See #188.
