### ISSUE TITLE
Audio issue pHat Dac RPi Zero

### ISSUE THREAD

**Issue by petitxef** [FD-/RPiPlay#183]
Hi!

I’m using a raspberry pi zero w with a Pimorini pHat DAC on a fresh install (raspberry Pi OS) and works fine, but not sound at all. 

I install the pHat DAC using the pimorini instructions:

https://learn.pimoroni.com/tutorial/phat/raspberry-pi-phat-dac-install

Any recommendation? 

Thanks!

**Comment by FD-** [comment]
DACs are not currently supported by RPiPlay on Raspberry Pi, at least not with the default OpenMAX renderers. See https://github.com/FD-/RPiPlay/issues/33.
