### ISSUE TITLE
4K resolution not showing up

### ISSUE THREAD

**Issue by seungjunProgramming** [FD-/RPiPlay#189]
Hi!
FIrst of all, thankyou for this great project!

I am using raspberrypi os on 4K with Raspberrypi4B 4GB model.
I can use 4K resolution with my TV, and it works.

BUt, on my mac, rpiplay only has 1080p resolution.
How can I add 4K resolution?

**Comment by FD-** [comment]
The AirPlay mirroring protocol is limited to 1080p, as can be witnessed by [multiple](https://discussions.apple.com/thread/250076156) [reports](https://apple.stackexchange.com/questions/302336/maximum-screen-resolution-with-airplay-extend-display-on-the-apple-tv-4k) [on the Internet](https://support.airserver.com/support/solutions/articles/43000529924-when-mirroring-to-airserver-the-resolution-is-1080p-even-though-my-device-has-a-much-higher-resoluti).
