### ISSUE TITLE
Running Headless and Desktopless

### ISSUE THREAD

**Issue by bobatrance** [FD-/RPiPlay#199]
Hi, I'm running RpiPlay on a Rasperry Pi Zero W. I have the lite version of the Raspbian OS installed. It's my understanding that the mirror requires a desktop environment (eg. gnome or pixel) or attached to a video out (mini HDMI in this case), correct? Is there no way to tap into the H264 stream and somehow cast it somewhere without either of these endpoints? I've seen discussion where people mentioning are running headless (presumably have desktops installed), as well as people mentioning running it through a VNC virtual desktop (which would fail in this case, since it would only find the bourne shell), and just wanted to make sure of the requirements. Thanks!

**Comment by pallas** [comment]
This project dumps to a Raspberry Pi's OMX/HDMI *or* to gstreamer. You might try to modify the gstreamer string to send it somewhere else, but that's beyond me.. I only use the OMX interface.
