### ISSUE TITLE
aacDecoder_DecodeFrame error : 0x400c

### ISSUE THREAD

**Issue by PawelBruski** [FD-/RPiPlay#20]
Hello,
thank you for the great software, it works perfect in screen mirroring mode. 
I've got only some issues trying to mirror spotify app to the AirPlay.
In the console I'm getting this output:
aacDecoder_DecodeFrame error : 0x400c
The sound's not playing.

![Zrzut ekranu 2019-09-18 o 22 16 36](https://user-images.githubusercontent.com/25956682/65182626-fc3c3d80-da61-11e9-9624-2f9474edd272.png)

BR,
Pawel

**Comment by FD-** [comment]
Duplicate of #2
