### ISSUE TITLE
insufficient resources?

### ISSUE THREAD

**Issue by ItsRogueRen** [FD-/RPiPlay#201]
I have been attempting to set this up on my desktop (Pop!_OS 20.10 running KDE Plasma) for several days not only to be met with the same error over and over again Terminal output is as follows

>rpiplay -vr gstreamer -ar gstreamer
>Initialized server socket(s)
>*** WARNING *** The program 'rpiplay' uses the Apple Bonjour compatibility layer of Avahi.
>*** WARNING *** Please fix your application to use the native API of Avahi!
>*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
>Accepted IPv4 client on socket 17
>Local: [redacted]
>Remote: [redacted]
>Accepted IPv4 client on socket 24
>Local: [redacted]
>Remote: [redacted]
>raop_rtp_mirror starting mirroring
>X Error of failed request:  BadAlloc (insufficient resources for operation)
>  Major opcode of failed request:  150 (XVideo)
>  Minor opcode of failed request:  19 ()
>  Serial number of failed request:  103
>  Current serial number in output stream:  104

All I'm trying to do is mirror an iPhone from the quick settings. I don't even care about the audio. 

Where do I get Avahi? Everything I can find is like 5 years old, I can't find an installation guide anywhere, everyone just keeps saying to use gstreamer which I already have installed!

I am TERRIBLE with anything source code so just spitting commands and saying "compile this" will just leave me more lost.

**Comment by pallas** [comment]
The Avahi thing is not an error, it's a warning, and not why you got a green screen. A search of the closed issues for this project makes that pretty clear. The real issue you're having is that some component in your X11 server is out of memory, specifically XVideo...

```
X Error of failed request: BadAlloc (insufficient resources for operation)
Major opcode of failed request: 150 (XVideo)
Minor opcode of failed request: 19 ()
Serial number of failed request: 103
```

This is a configuration issue, but not with RPiPlay.
