### ISSUE TITLE
GStreamer not recognized (Arch Linux)

### ISSUE THREAD

**Issue by ThatFruedDued** [FD-/RPiPlay#211]
Hello,
When I run RPiPlay, GStreamer does not seem to be recognized. I am running Arch Linux and I have verified that GStreamer is installed and working. 
![Screenshot_20210111_142833](https://user-images.githubusercontent.com/57722939/104229474-5660cf00-541a-11eb-8671-95334d6afce4.png)
All of the other features of the app work. I can connect to RPiPlay from devices, I just cannot view the display of the device or listen to the audio (although audio support is not a necessity for me).
How can I fix this, or is this simply incompatibility with Arch Linux? Thanks!

**Comment by SyzSteM** [comment]
If you want, you can take a look at my AUR package of this project here: [rpiplay-git](https://aur.archlinux.org/packages/rpiplay-git/).
Maybe you are missing the gstreamer bad plugins (gst-plugins-bad)? You could try to install my package from the AUR, it tested it on clean arch.
Cheers!

**Comment by ThatFruedDued** [comment]
@SyzSteM I'll look into yours! I have gst-plugins-bad installed, so I'm unsure why it's not working.

**Comment by ThatFruedDued** [comment]
@SyzSteM no luck. Could it have to do with conflicts with KDE Plasma? Thanks for your help!

**Comment by ThatFruedDued** [comment]
I got it! I used your AUR package, and now it displays on my laptop. Thanks!
