### ISSUE TITLE
Can't quit when set to autostart

### ISSUE THREAD

**Issue by ungeschneuer** [FD-/RPiPlay#22]
I followed the instructions on your wiki page (https://github.com/FD-/RPiPlay/wiki/Starting-RPiPlay-at-system-start) to autostart RPiPlay but now I can't quit it with Ctrl + C anymore. I guess because the terminal is not taking the keys in the background.

**Comment by FD-** [comment]
It's working fine for me. The described solution doesn't start the program in the background, so I'm not sure I understand your last sentence.

**Comment by fhopfensperger** [comment]
I solved the background program thing with a cronjob when the raspberry boots (sleeps for 20 secs to make sure everything is up and running before `rpiplay` starts).
`crontab -e`
add the follwing line
`@reboot sleep 20;/home/pi/RPiPlay/build/rpiplay -n airplay -a hdmi -b > /dev/null 2>&1`

**Comment by FD-** [comment]
@fhopfensperger But with that solution, Ctrl+C doesn't work for stopping RPiPlay, right?

**Comment by fhopfensperger** [comment]
yes you're right, I use that command to kill `RPiPlay`, because the program is running in the background.
`kill $(ps aux | grep [r]piplay | awk '{print $2}')`

**Comment by FD-** [comment]
@fhopfensperger I see. What I'm using is `killall -9 rpiplay`. That's a bit shorter and also works in the case that rpiplay has got stuck somewhere.

**Comment by fhopfensperger** [comment]
even better. btw. thank you for this great software.

**Comment by cropd** [comment]
You could also create a systemd service and start/stop the service or enable it to start it on system boot.

**Comment by FD-** [comment]
@cropd Yeah, but stopping it without remote access would be more difficult while RPiPlay overlays the terminal (than the way described in the wiki).

**Comment by cropd** [comment]
@FD- I see... my Pi runs RPiPlay behind my beamer – so remote access is needed – and it starts when powering my beamer on... love it! thank you for this project!!
