### ISSUE TITLE
Video cannot be reproduced from TV+ app

### ISSUE THREAD

**Issue by jcconca** [FD-/RPiPlay#225]
After installing the service, almost everything is fine:

iPhone XR mirroring
iPad 4 mirroring

iPhone photos, sometimes hangs video, get frezed and then recover and share it. But that is not the case.

I can even see the application youtube on full screen mirroring.

But when I try to reproduce TV+ in the rpiplay, the error says something like, the screen has not authorisation to reproduce protected films

![F298ADFA-72E8-4F55-ABAF-B4074CA19F14](https://user-images.githubusercontent.com/8432547/109344512-1d1bdb80-786f-11eb-8207-edb599922b72.png)

If I disable the screen mirroring and try to send directly the video, I can see errors in the console saying:
aacDecoder_DecoderFrame error : 0x400c
aacDecoder_DecoderFrame error : 0x4002

![7DA8F2DA-6102-4BEE-81F3-464953404C7E](https://user-images.githubusercontent.com/8432547/109345088-e5616380-786f-11eb-9c14-912df3bff303.jpeg)

No video or audio sent to the raspberry.

Is a known incompatibility with the application or is the content?

**Comment by FD-** [comment]
I suspect the problem is issue #7.

**Comment by jcconca** [comment]
@FD- thanks for the quick reply.

I will have a look into the the related problem. I’m rusty with C, but if I can help I will try
