### ISSUE TITLE
Wrong aspect ratio when no monitor is plugged in

### ISSUE THREAD

**Issue by asxic** [FD-/RPiPlay#23]
I have noticed that when I launch RPiPlay without any monitor plugged into my rpi the aspect ratio isn't right (see picture below). I know it's not a big issue because there are basically no reasons to use this software without a monitor, but I just wanted to tell you about that.

Keep your hard work, what you are doing is awesome !

![image](https://user-images.githubusercontent.com/29875292/65812999-40041500-e1cf-11e9-8a69-85b55bbbd975.png)

**Comment by FD-** [comment]
AFAICT, this is an issue with the Pi itself, not with this software. I'm seeing the same behavior with the Raspbian Desktop: Attaching the monitor after boot leads to odd low-res image, while booting with monitor attached has the Pi display proper 1080p. Probably could be solved by hard-coding the monitor resolution in /boot/config.txt.
