### ISSUE TITLE
Keyboard shortcut to exit?

### ISSUE THREAD

**Issue by CleanMachine1** [FD-/RPiPlay#234]
Title says all, whilst inside RPiPlay, what is the correct way to close it and get back to desktop

**Comment by Itai-Nelken** [comment]
this is something very important in my opinion.

**Comment by FD-** [comment]
Ctrl + C should work fine (it does for me).

**Comment by CleanMachine1** [comment]
What about when running it not from a terminal?

**Comment by FD-** [comment]
Well, RPiPlay doesn't even have a window, so a shortcut wouldn't make any sense IMO.

**Comment by CleanMachine1** [comment]
If there is no way to do it without a terminal, I guess I will have to find a different way, regardless thank you for your response

**Comment by tamborello** [comment]
Ctrl-C does not quit RPiPlay for me. What else might quit RPiPlay?
