### ISSUE TITLE
Remotely connected to PI using VNC

### ISSUE THREAD

**Issue by pjsf1000** [FD-/RPiPlay#236]
Hi 

I don't have a direct HDMI screen on my raspberryPI, rather I remotely connect to the screen using VNC Server/Client.

I have got as far as installing RPiPlay,  and I have enabled Mirror on ipad which RPIplay seems to accept
"Accepted IPv4 client on socket 15"

The problem is that I don't see any screen mirroring on the VNC client and/or Pi Desktop.

Should it work, or is doing this over VNC not supported?

**Comment by FD-** [comment]
Duplicate of #221
