### ISSUE TITLE
Can't build because ld can't find dns_sd.so

### ISSUE THREAD

**Issue by bigjeff96** [FD-/RPiPlay#238]
When I first tried to build the executable, I got the same problem as https://github.com/FD-/RPiPlay/issues/210, and so I just downloaded the dns_sd.h file and put in the lib/ directory. Then I got a different error compared to https://github.com/FD-/RPiPlay/issues/210, I needed to download the plist.h and do the sam thing again.
After almost finishing the build, I got this error
```
[ 14%] Built target renderers
[ 31%] Built target playfair
[ 42%] Built target llhttp
[ 94%] Built target airplay
[ 97%] Linking CXX executable rpiplay
 ~/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: cannot find -ldns_sd
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/rpiplay.dir/build.make:90: rpiplay] Error 1
make[1]: *** [CMakeFiles/Makefile2:162: CMakeFiles/rpiplay.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by rogercorrea** [comment]
Install the libraries:

`sudo apt-get install libavahi-compat-libdnssd-dev`
