### ISSUE TITLE
Feature Request: Make a build for steamlink hardware

### ISSUE THREAD

**Issue by pharmville** [FD-/RPiPlay#239]
Steamlink SDK for developers: https://github.com/ValveSoftware/steamlink-sdk

**Comment by FD-** [comment]
You're welcome to tackle the port on your own, but I'm afraid no-one else will be interested in investing time into developing a new pair of renderers (The steamlink likely is not powerful enough for gstreamer and obviously the Pi-specific OpenMAX ilclient code won't work there) for a legacy platform.
