### ISSUE TITLE
Decoding artifacts when using gstreamer

### ISSUE THREAD

**Issue by gamelaster** [FD-/RPiPlay#240]
![image](https://user-images.githubusercontent.com/1665373/115349391-15641d80-a1b4-11eb-94c8-65a9bd55ca8e.png)

OS: Ubuntu 20.04 (x86_64, virtual machine)
Phone: iPhone 7 (iOS 14)

For some reason, when using gstreamer, I have those artifacts. It looks like pixel format or width & height of received data is somehow broken. This also might be issue because of Virtual Machine, although, hard to say. Will investigate more later.

**Comment by dougg3** [comment]
I actually ran into this problem as well and [wrote a blog post about it](https://www.downtowndougbrown.com/2021/04/finding-and-fixing-a-vmware-xorg-video-display-bug-using-gstreamer/). It’s a problem with VMware’s Xorg plugin, which is also used by VirtualBox in certain conditions. I submitted a patch but it hasn’t been accepted yet.

**Comment by gamelaster** [comment]
@dougg3 wow, really amazing work finding out what is the issue! 😊 

Well, since it looks like it's Xorg issue, let's close this.

Thanks

**Comment by FD-** [comment]
Thanks @dougg3! Really impressive work you did there!

**Comment by dougg3** [comment]
Thanks! My patch seems kind of stuck in limbo, I’m not sure if the VMware plugin has a maintainer right now. For now you could hack the code to use glimagesink instead of autovideosink and it should work better.
