### ISSUE TITLE
Fail to install on arm64 debian buster platform

### ISSUE THREAD

**Issue by xmasrain** [FD-/RPiPlay#270]
root@openmediavault:/home/pi/RPiPlay/build# sudo make install
[  3%] Built target h264-bitstream
[  7%] Built target playfair
[ 10%] Built target llhttp
[ 22%] Built target airplay
[ 24%] Built target ilclient
[ 93%] Built target fdk-aac
[ 98%] Built target renderers
[ 99%] Linking CXX executable rpiplay
/usr/bin/ld: /opt/vc/lib/libbrcmGLESv2.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/rpiplay.dir/build.make:99\uff1arpiplay] \u9519\u8bef 1
make[1]: *** [CMakeFiles/Makefile2:79\uff1aCMakeFiles/rpiplay.dir/all] \u9519\u8bef 2
make: *** [Makefile:130\uff1aall] \u9519\u8bef 2

**Comment by alexmyczko** [comment]
https://sid.ethz.ch/debian/rpiplay/arm64/ built perfectly for me (but used bullseye on arm64).
