### ISSUE TITLE
upgrade to OpenSSL 3.0.0 causes stuttering audio

### ISSUE THREAD

**Issue by fduncanh** [FD-/RPiPlay#274]
The new OpenSSL 3.0.0 (with GPLv3 compatible Apache license) makes some changes in libcrypto
that disagree with RPiPlay:     

After getting OpenSSL 3.0.0 by installing Debian unstable packages  libssl3 + libssl-dev + openssl on ubuntu 20.04,
RPiPlay builds without problem, and ldd rpiplay shows libcrypto.so.3 (instead of libcrypto.so.1.1 in an openssl-1.1.1x build).

But streamed music has audio stuttering with the openssl3.0.0 build that is not there with the 1.1.1 build, so libcrypto changes are breaking something.   This is on linux desktop, with gstreamer rendering, but since libcrypto is only used  in the airplay raop library, it shouldn't depend on the renderer.    Using OpenSSL 3.00 built from source behaves identically.

It would be great if anyone here who is a libcrypto expert could find what the issue is.   The openssl3 release notes
state that some things in applications  may break and need to be fixed after the upgrade.

OpenSSL3  is the future, as it removes the license obstacle to distribution of compiled GPLv3 code linked to OpenSSL. 
(I am interested in the change, because someone wants to package UxPlay 1.38 (which I maintain) for debian, which is only possible with OpenSSL3, but  I am no libcrypto expert)

OpenSSL 1.1.1 will be maintained for another 2 years only.

**Comment by fduncanh** [comment]
Some more clues to this.

(1) The problem must be in lib/crypto.c where the only direct link to openssl is made.

(2)  It must be in the "common AES Utilities" used by raop_buffer.c and mirror_buffer
which are  are used for decrypting the streamed audio and video (as opposed to the ellitptic curve crypto
which is used for the initial pairing between server and client.)

(3) more evidence for this is that the original antimof version of the RPiPlay fork  uxplay http://github.com/antimof/UxPlay  has exactly the same problem with OpenSSL 3.0.0, but it uses an older version of the RPiPlay crypto.c where the elliptic curve stuff is not in crypto.c, and not handled by openssl.  In this case basically the only things in crypto.c  are the "common AES Utilities".
Maybe the best strategy to find what needs to be fixed might be the get the antimof uxplay (or an older  version of RPiPlay) working with OpenSSL 3.0.0, and then port the fix to current RPiPlay and UxPlay.

(4) Its not obvious from the OpenSSL 3.0.0 migration guide
https://www.openssl.org/docs/man3.0/man7/migration_guide.html
where the problem might be.

**Comment by fduncanh** [comment]
@FD-

One possibility (that was seen in some other reported OpenSSL 1.1.1->3.0.0 migration issue is that there is a bug in crypto.c that somehow doesnt cause an error in OpenSSL-1.1.1,  but does in OpenSSL3.0.0 which has stricter internal consistency_.

This suggests that one should try to validate FD-'s code for "Common AES utilities" in crypto.c when linked to  OpenSSL 3.0.0.
as  compared to OpenSSL-1.1.1

 One strange thing I noticed is

```
void aes_ctr_encrypt(aes_ctx_t *ctx, const uint8_t *in, uint8_t *out, int len) {
    aes_encrypt(ctx, in, out, len);
    ctx->block_offset = (ctx->block_offset + len) % AES_128_BLOCK_SIZE;
}

void aes_ctr_start_fresh_block(aes_ctx_t *ctx) {
    // Is there a better way to do this?                                                                                                                            
    if (ctx->block_offset == 0) return;
    aes_ctr_encrypt(ctx, waste, waste, AES_128_BLOCK_SIZE - ctx->block_offset);
}

void aes_ctr_decrypt(aes_ctx_t *ctx, const uint8_t *in, uint8_t *out, int len) {
    aes_encrypt(ctx, in, out, len);                       <==========================?? encrypt not decrypt????
}

void aes_ctr_reset(aes_ctx_t *ctx) {
    aes_reset(ctx, EVP_aes_128_ctr(), AES_ENCRYPT);
}

void aes_ctr_destroy(aes_ctx_t *ctx) {
    aes_destroy(ctx);
}
```

compared to

```

void aes_cbc_encrypt(aes_ctx_t *ctx, const uint8_t *in, uint8_t *out, int len) {
    assert(ctx->direction == AES_ENCRYPT);
    aes_encrypt(ctx, in, out, len);
}

void aes_cbc_decrypt(aes_ctx_t *ctx, const uint8_t *in, uint8_t *out, int len) {
    assert(ctx->direction == AES_DECRYPT);
    aes_decrypt(ctx, in, out, len);
}

void aes_cbc_reset(aes_ctx_t *ctx) {
    aes_reset(ctx, EVP_aes_128_ctr(), ctx->direction);
}

void aes_cbc_destroy(aes_ctx_t *ctx) {
    aes_destroy(ctx);
}

```

But just changing that "encrypt" to "decrypt" triggers an error. so maybe its a bug compensated by a second bug?
(? maybe because AES is symmetric?)

**Comment by pallas** [comment]
Does adding `-DOPENSSL_NO_AES_CONST_TIME` make a difference?

**Comment by fduncanh** [comment]
From the OpenSSL commit message  for this:
This  seems to require rebuilding OpenSSL 3.0.0 with "no-asm"

I'll check it out

```
This adds optional constant time support for AES
when building openssl for no-asm.

Enable with: ./config no-asm -DOPENSSL_AES_CONST_TIME
Disable with: ./config no-asm -DOPENSSL_NO_AES_CONST_TIME

This is by default enabled.
```
The  OpenSSL3  INSTALL.md says

```
no-asm 
Do not use assembler code. 
This should be viewed as debugging/troubleshooting option rather than for production use. On some platforms a small amount of assembler
code may still be used even with this option. 
```

**Comment by fduncanh** [comment]
Fixing the  bug  in codec.c reported as #283 with a small workaround in lib/buffer.c fixed the problem with OpenSSL3

For AES_CTR, the OpenSSl; decrypter EVP_DecryptUpdate really need to be followed by EVP_DecryptFinal
but the workaround of calling aes_ctr_decrypt with a buffer size of encryptlen + 15 instead of encryptlen  makes OpenSSL do its work properly.   Unfortunately FD--'s crypto.c implementation zeroed out the last 16 encrypted bytes without this fix. 

 A by-product of the fix is that has become trivial to add back support for ALAC (as in shairplay) to RPiPlay.
