### ISSUE TITLE
iPad--(WiFi)-->Android Phone--(USB)-->PC with RPiPlay

### ISSUE THREAD

**Issue by p135246** [FD-/RPiPlay#281]
My iPad is connected over WiFi to my Android phone which serves as a mobile hostpost. The Android phone is connected to my PC via USB-tethering. I would like to use RPiPlay to mirror the screen of my iPad on the PC. However, the iPad does not detect any Airplay receiver. Is it possible to make this configuration work and how? Thank you very much.

**Comment by pallas** [comment]
My guess (with no evidence) is that if you are actually connected you're still failing to do multicast through the tether, which is required for discovery.
