### ISSUE TITLE
Airpods Pro with RpiPlay

### ISSUE THREAD

**Issue by abdullahaltun70** [FD-/RPiPlay#297]
Hi,

I've got RPiPlay to work on my RPI2 with Buster Lite installed on it. 
The issue I'm facing is: Every time I connect my airpods to my iPhone(IOS 15) RPiPlay disconnects en then my airpods connects. When I switch back and connect RPiPlay my airpods disconnect.

Is there a way I can use RPiPlay with my airpods also connected to my phone?

**Comment by FD-** [comment]
I suspect the same behavior can also be observed for connections with official AirPlay Mirroring servers.
