### ISSUE TITLE
mirroring using RPiPlay without hdmi or another physical connection

### ISSUE THREAD

**Issue by labirinth30** [FD-/RPiPlay#313]
I'm not sure its the right place to ask this but is it possible?
TV and Raspberry are in different rooms, so is there any solution to mirror my iPhone/mac screen to the TV (Sony Android TV) without having to connect the raspberry to the TV with a cable (HDMI)?

**Comment by FD-** [comment]
You'd better install an AirPlay server on the TV (Some Sony TVs already ship with one installed). RPiPlay doesn't support this scenario.
