### ISSUE TITLE
Doesn't Turn On Blackscreen

### ISSUE THREAD

**Issue by lnn2204** [FD-/RPiPlay#322]
Hi guys, I'm using Rasp 4B, 2GB of RAM, and it running RaspOS Desktop (Bulleyes). I used "./rpiplay -b on" but it not turn on the blackscreen. Any solution please...

**Comment by RodargDev** [comment]
Im having the same problem man raspberry pi 4 8gb fresh raspOS not working at all

**Comment by taras-sereda** [comment]
I had same problem with **bulleyes**, but it works fine with **Buster**.

Some more extra steps are needed to make it working on **bulleyes**, check this comment: https://github.com/FD-/RPiPlay/issues/296#issuecomment-981210609
