### ISSUE TITLE
Fresh install

### ISSUE THREAD

**Issue by Niutonian** [FD-/RPiPlay#325]
Hello, 
How do I remove RPIPlay from a Raspberry Pi running Raspbian to replace it with another version?

I want to use the flatsieDatsie fork, but it keeps on reloading the initial install
https://github.com/flatsiedatsie/RPiPlay

Thank you

**Comment by pallas** [comment]
You find where you installed the binary and overwrite it. Note that the fork you mentioned is very far behind FD-'s mainline, including security fixes.
