### ISSUE TITLE
RPiPlay running on WIndows WSL2 - IOs Device cannot find RPiPlay

### ISSUE THREAD

**Issue by OliveiraICTS** [FD-/RPiPlay#329]
Hello,

I installed a Ubuntu 20.04 on Windows 11 WSL2. After that follow all README.md steps and could build and install RPiPlay on it.
When I run, looks okay, but the mobile with it feature cannot find rpliplay server.

**Comment by FD-** [comment]
This scenario is not supported (untested) atm.
