### ISSUE TITLE
RPiPlay - can be builded on WIndows to genarate rpiplay.exe?

### ISSUE THREAD

**Issue by OliveiraICTS** [FD-/RPiPlay#330]
Hi,
I See inside your code that exists macros WIN32 e WIN64, so, I understand that is possible to build it on WIndows. 

It is possible?

If yes, what procedure I have to do to generate a rpiplay.exe

Regards,

**Comment by fduncanh** [comment]
RPiPlay is derived from dsafa22's code,  still found at https://github.com/jiangban/AirplayServer (seems to support android and windows)

What appears to be a rewrite of the dsafa22 code in C# for windows is found at https://github.com/SteeBono/airplayreceiver
