### ISSUE TITLE
Output only while casting

### ISSUE THREAD

**Issue by baramuse** [FD-/RPiPlay#37]
Hi !

I was wondering if there was any way to be able to launch in background in a way that it would only output an image if there is something casting/connected
I don't know the underlying of using the HDMI output, but what if I want to have my KODI running but RPiPlay taking over when casting ?

Cheers for your awesome work!

**Comment by FD-** [comment]
If you start RPiPlay with the -b flag, it will keep a transparent background and only draw when a connection is active. However, I suspect it still won't work with KODI since IIRC both draw through the GPU and there's some layer issue (haven't tried myself).

**Comment by baramuse** [comment]
> If you start RPiPlay with the -b flag, it will keep a transparent background and only draw when a connection is active. However, I suspect it still won't work with KODI since IIRC both draw through the GPU and there's some layer issue (haven't tried myself).

I'll test tonight then, thanks :)

**Comment by baramuse** [comment]
I works like a charm !
Well, quite... if the casted is full screen then we won't see Kodi behind, but if the casted is an iPhone for example, we'll see kodi backgroup (pretty fun though..)
So maybe we could have a third background option : only draw a black background when the cast started ?

**Comment by FD-** [comment]
This should be pretty easy to add, probably as an additional parameter to the -b flag.

**Comment by Dulatech** [comment]
> I works like a charm !
> Well, quite... if the casted is full screen then we won't see Kodi behind, but if the casted is an iPhone for example, we'll see kodi backgroup (pretty fun though..)
> So maybe we could have a third background option : only draw a black background when the cast started ?

Hello @baramuse,

Were you able to change the application to allow for the black background to only show up when the cast started?

**Comment by moda20** [comment]
@baramuse how do you run it on Kodi ? do you build elsewhere then transfer the executable ? what do you do exactly ?

**Comment by FD-** [comment]
Added by #50.

**Comment by baramuse** [comment]
> @baramuse how do you run it on Kodi ? do you build elsewhere then transfer the executable ? what do you do exactly ?

I just run RPIPlay in background and then run Kodi on top

**Comment by moda20** [comment]
@baramuse ah I thought you created a plugin or something
