### ISSUE TITLE
Multiple devices

### ISSUE THREAD

**Issue by stefano055415** [FD-/RPiPlay#38]
if I try to connect 2 raspberry with rpi play on the same network, with different names, one of the two stops working, but only if started at boot.
if they are started manualmente work correctly

**Comment by FD-** [comment]
That sounds very much like some problem with your specific script/setup. Does adding a delay after boot before starting RPiPlay fix the problem?

**Comment by cleeland** [comment]
Is it possible that dnssd advertisements are clashing?

**Comment by pallas** [comment]
stale
