### ISSUE TITLE
YouTube steaming

### ISSUE THREAD

**Issue by thomas192000** [FD-/RPiPlay#43]
Als ik een video van YouTube wil streamen van af mijn iPhone dan blijft het laad scherm ik krijg geen video te zien op de Raspberry pi 3

**Comment by FD-** [comment]
Please either post your comment in English or I'll close this issue. I'm not willing to communicate via Google translate.

**Comment by thomas192000** [comment]
If i want to stream a video from YouTube from my iPhone to thé raspberry, the loading screen remains. I can't see a video on the Raspberry pi 3
