### ISSUE TITLE
The program 'rpiplay' uses the Apple Bonjour compatibility layer of Avahi.

### ISSUE THREAD

**Issue by marcofranssen** [FD-/RPiPlay#51]
Initialized server socket(s)
*** WARNING *** The program 'rpiplay' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=rpiplay>

How to resolve this? The link doesn't work. I did follow the build instructions and run all from my Raspberry Pi 3.

Furthermore when mirroring my Apple Macbook (Catalina) it only mirrors the video. The audio doesn't work somehow. I'm happy to provide any info required to resolve that.

My audio is using the hdmi connection to my television. This works for Kodi which also runs on my raspberry pi.

I also tried from my iphone 6 to mirror the screen but it doesn't detect this airplay device. Any thoughts on that? 

As soon something hangs, only way to recover is a `kill -9`. Same as someone else mentions in a another issue.

**Comment by FD-** [comment]
1. The Bonjour message is only a warning shown by the libavahi-compat-dnssd library, with no implications on functionality
2. Did you set the correct audio port on RPiPlay via the -a flag?
3. Are both devices in the same network?
4. Known issue

**Comment by pallas** [comment]
Note: `export AVAHI_COMPAT_NOWARN=1`
