### ISSUE TITLE
Great job. Everything just worked.

### ISSUE THREAD

**Issue by danielbalog** [FD-/RPiPlay#52]
I don't have an issue at all, but I didn't know what the best way to thank you was.

I just built this on my Rasberry Pi 3B+. Installation was easy. Hooked it up to my TV and it just worked.

I tried with my iPhone XR and my MacBook Pro, and both just worked extremely fast with barely any lag at all. I could run both video and audio. Honestly blew my mind.

I'm so glad I discovered this. Keep up the good work!

( Feel free to close this as resolved ;-) )

**Comment by patientzero** [comment]
Same as my @danielbalog.
Just thanks a lot. After battling with other solutions the last couple of years, this just worked!
So Thank you!

**Comment by alistarle** [comment]
Same for me, this project is setup on my pi in less than 5 minutes and works like a charm, good work dude !

**Comment by iDoka** [comment]
What I could say about this project?
It just worked!!! Amazing!
Build instruction is clear and fine!
@FD-  Many thanks for this repo!

**Comment by rerpha** [comment]
+1, Have used this on both a RPi model 2B and a Zero W 1.1, works really nicely on both!

**Comment by kirschem** [comment]
+++
Also worked great for me, many thanks! Sound and video from my iPhonxe XS worked out of the box with Model 3.

I just made a simple script to automate the installation and add the server to autostart: 
https://github.com/kirschem/install-rpiplay

**Comment by pallas** [comment]
Glad to hear it!
