### ISSUE TITLE
Rotate image 90 degrees

### ISSUE THREAD

**Issue by wimrigo** [FD-/RPiPlay#54]
My screen is standing up vertically but when I cast it shows the image horizontally. Is there a way to flip the image?

**Comment by rcarmo** [comment]
Do you have `display_rotate` in your `config.txt`? That is how the Pi knows how to rotate conventional text and graphics.

**Comment by wimrigo** [comment]
display_rotate isn't working on my PI4. I've read that it isn't supported for PI4.
I rotate my screen via 'preferences'

**Comment by rcarmo** [comment]
Ah. So you’re doing it at the X11/RandR level most likely, not the framebuffer/hardware level.

**Comment by wimrigo** [comment]
Like they mention in the link below it is not possible due to the new video driver they use:(https://pimylifeup.com/raspberry-pi-rotate-screen/)

**Comment by FD-** [comment]
This is probably trivial to do, just by setting the [OMX_IndexConfigCommonRotate](http://www.jvcref.com/files/PI/documentation/ilcomponents/video_render.html) config on the OpenMAX renderer component. I'd suggest adding a -r {degree} argument to the cmdline.

**Comment by StevenHickson** [comment]
Any more insight into how to do this?
I tried adding the following to the file *renderers/video_renderer_rpi.c* and it just fails to initialize:
```
    // Setup rotation
    OMX_CONFIG_ROTATIONTYPE rotation;
    memset(&rotation, 0, sizeof(OMX_CONFIG_ROTATIONTYPE));
    rotation.nRotation = 90;
    rotation.nPortIndex = 91;
    if (OMX_SetParameter(ilclient_get_handle(renderer->video_renderer), OMX_IndexConfigCommonRotate,
                         &rotation) != OMX_ErrorNone) {
        video_renderer_destroy_decoder(renderer);
        return -15;
    }
```

I also tried adding the transform to the DisplayRegion per the docs with the line:
```
display_region.transform = OMX_DISPLAY_ROT90;
```
That seems like it should work based off of this documentation:
https://github.com/adafruit/rpi-firmware/blob/master/vc/sdk/opt/vc/include/IL/OMX_Broadcom.h
but it just does nothing and keeps the normal rotation.

**Comment by StevenHickson** [comment]
Actually I figured this out and submitted a PR#58 for it.

**Comment by wimrigo** [comment]
@StevenHickson What do you mean with a PR#58?

**Comment by StevenHickson** [comment]
Pull Request.
https://github.com/FD-/RPiPlay/pull/58
You can change the number on line 279 rotation.nRotation = -90 to suit your rotation. The way to do this cleanly would probably be to allow the rotation number as the command line flag but I'm waiting to hear from the author before doing anything like that.

You should be able to grab that pull request and run a rotated version. It is working perfectly well for me at home.

**Comment by wimrigo** [comment]
I copied those 4 files and started rpiplay this way: ./rpiplay -n cast -r
Unfortunately when I cast there is no rotation. Am I doing something wrong?

**Comment by wimrigo** [comment]
@StevenHickson I copied those 4 files and started rpiplay this way: ./rpiplay -n cast -r
Unfortunately when I cast there is no rotation. Am I doing something wrong?

**Comment by StevenHickson** [comment]
You need to recompile. An updated #67 let's you chose the rotation amount. You can also pull that specific patch or pull request and compile.

**Comment by FD-** [comment]
Merged now.
