### ISSUE TITLE
There is no device, when i scan in Screen mirroring by Iphone 7 

### ISSUE THREAD

**Issue by Sandro-cpu** [FD-/RPiPlay#55]
I've installed rpi on Raspberry 3 b+, after I launch it, got log:

Initialized server socket(s)
*** WARNING *** The program 'rpiplay' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see http://0pointer.de/blog/projects/avahi-compat.html

but there is no device in Screen mirroring list, How I can connect it

**Comment by FD-** [comment]
Make sure both devices are on the same network. If they are, some other third-party AirPlay (or other Bonjour service) might interfere. Try setting up an isolated network for testing.
