### ISSUE TITLE
Can't install on Armbian - Orange Pi

### ISSUE THREAD

**Issue by rozzimann96** [FD-/RPiPlay#57]
Please make version for Orange Pi (PC +) on Armbian....
"cmake .." command end with errors and not be configured.

**Comment by FD-** [comment]
RPiPlay was built specifically for the Raspberry Pi‘s Video decoding hardware. I don’t have any plans to port it to another SBC platform, but if someone contributes a generic Linux renderer that happens to work with a HW-accelerated backend on the Orange Pi, the situation might change. Alternatively, you’re welcome to contribute an Orange Pi specific renderer.
