### ISSUE TITLE
Question - saving frames to disk

### ISSUE THREAD

**Issue by bduclaux** [FD-/RPiPlay#62]
Hello,

Great project ! 
I would like to know if it would be easy to modify the code in order to save each frame into a file (eg frame_0001.jpg, frame_0002.jpg, etc.). As Jpeg compression could consume a lot of CPU, raw bitmap format could be ok too.

Is there a specific location in the code where I could insert a callback to save the current frame into a file, while incrementing a frame counter ?

Thanks for your help

**Comment by FD-** [comment]
I won't add an option for this, but you should be able to get what you want by dumping the H264 stream using the flags in the code and using whatever program can do it to extract stills from it.
