### ISSUE TITLE
Cannot connect RaspberryPi

### ISSUE THREAD

**Issue by aroxu** [FD-/RPiPlay#64]
Hello. Newbie here.
I've build according to the README.md and successfully build the file.
But when i try to connect, it always say "Cannot connect to `RaspberryPi`"
How can I solve it?

**Comment by FD-** [comment]
Try it again (sometimes only work on second attempt) or reboot Pi and iOS device.

**Comment by pallas** [comment]
This is not detailed enough to resolve.
