### ISSUE TITLE
Airplay via wifi not working

### ISSUE THREAD

**Issue by mrwrighty** [FD-/RPiPlay#69]
This is a great tool and solved a major problem for us, however I’m only able to get it working via Ethernet. If I use WiFi, the AirPlay name is displayed on the iOS device, but when selected, the screen remains blank and the iOS device times out unable to connect. I’ve tried 2.4 and 5mhz neither work. Any suggestions. Many thanks.

**Comment by FD-** [comment]
Likely something going on in your network that prevents RPiPlay from working. I suggest setting up a separate WiFi network for testing with just the Pi and iOS device.
