### ISSUE TITLE
AirParrot Segmentation fault.

### ISSUE THREAD

**Issue by cloudykeyru** [FD-/RPiPlay#76]
osmc@osmc:~/Downloads/RPiPlay/build$ ./rpiplay -b auto -n appleTV
Initialized server socket(s)
*** WARNING *** The program 'rpiplay' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=rpiplay>
Accepted IPv4 client on socket 15
Local: 10.0.10.21
Remote: 10.0.10.31
raop_rtp_mirror starting mirroring
Accepted IPv4 client on socket 18
Local: 10.0.10.21
Remote: 10.0.10.31
raop_rtp starting audio
Segmentation fault

Error on connection.

OUTPUT WITH DEBUG
osmc@osmc:~/Downloads/RPiPlay/build$ ./rpiplay -b auto -n appleTV -d
> stream info: channel = 2      sample_rate = 44100     frame_size = 480       aot = 39 bitrate = 0
Initialized server socket(s)
*** WARNING *** The program 'rpiplay' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=rpiplay>
Accepted IPv4 client on socket 15
Local: 10.0.10.21
Remote: 10.0.10.31
httpd receiving on socket 15
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 15
conn_request
Handling request POST with URL /pair-setup
httpd receiving on socket 15
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 15
conn_request
Handling request POST with URL /pair-verify
httpd receiving on socket 15
conn_request
Handling request POST with URL /fp-setup
httpd receiving on socket 15
conn_request
Handling request POST with URL /fp-setup
httpd receiving on socket 15
conn_request
Handling request GET with URL /info
INFO len = 1935644780
httpd receiving on socket 15
conn_request
Handling request SETUP with URL rtsp://10.0.10.21/288
Transport: null
SETUP 1
eiv_len = 16
ekey_len = 72
fairplay_decrypt ret = 0
timing_rport = 7010
raop_ntp parse remote ip = 10.0.10.31
raop_ntp starting time
raop_rtp parse remote ip = 10.0.10.31
raop_rtp_mirror parse remote ip = 10.0.10.31
eport = 39721, tport = 56623
type = 110
streamConnectionID = 288
raop_ntp send_len = 32
raop_rtp_mirror starting mirroring
Mirroring initialized successfully
raop_ntp receive time type_t packetlen = 32
raop_ntp sync correction = -2208988800009399
httpd receiving on socket 15
conn_request
Handling request RECORD with URL rtsp://10.0.10.21/288
raop_handler_record
httpd receiving on socket 15
conn_request
Handling request GET with URL /info
INFO len = 1935644780
Accepted IPv4 client on socket 18
Local: 10.0.10.21
Remote: 10.0.10.31
httpd receiving on socket 15
conn_request
Handling request POST with URL /feedback
raop_handler_feedback
raop_rtp_mirror accepting client
httpd receiving on socket 15
conn_request
Handling request SETUP with URL rtsp://10.0.10.21/41
Transport: null
SETUP 1
eiv_len = 16
ekey_len = 72
fairplay_decrypt ret = 0
timing_rport = 51965
raop_ntp parse remote ip = 10.0.10.31
raop_ntp starting time
raop_rtp parse remote ip = 10.0.10.31
raop_rtp_mirror parse remote ip = 10.0.10.31
eport = 39721, tport = 40051
type = 96
raop_rtp starting audio
RAOP initialized success
raop_ntp send_len = 32
raop_ntp receive time type_t packetlen = 32
raop_ntp sync correction = -2208988800009478
raop_rtp_mirror width_source = 1920.000000 height_source = 1080.000000 width = 1827.571533 height = 1027.571533
raop_rtp_mirror sps size = 24
raop_rtp_mirror pps size = 4
Got h264 data of 36 bytes
Injecting max_dec_frame_buffering
Video delay is 1584340100206798
raop_rtp_mirror video ntp = 2464233090198212, now = 1584340100215613, latency = -879892989982599
Got h264 data of 159129 bytes
Video delay is -879892989978877
Video delay is -879892989978180
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
raop_rtp type_c 0x54, packetlen = 20
raop_rtp sync: ntp=18446119425009784460, local ntp: 1584340100242322, rtp=1584326870, rtp_next=1584340100
raop_rtp sync correction=-1584304174462957
raop_rtp audio: ntp = 1584340100542322, now = 1584340100256600, latency=-285722, rtp=1584340100
Got AAC data of 11 bytes
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
raop_rtp_mirror video ntp = 2464233090254221, now = 1584340100259312, latency = -879892989994909
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
Got h264 data of 51 bytes
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Video delay is -879892989993070
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
raop_rtp audio: ntp = 1584340100553206, now = 1584340100264652, latency=-288554, rtp=1584340580
Got AAC data of 9 bytes
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
raop_rtp audio: ntp = 1584340100564090, now = 1584340100272427, latency=-291663, rtp=1584341060
Got AAC data of 10 bytes
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
raop_rtp audio: ntp = 1584340100564090, now = 1584340100281790, latency=-282300, rtp=1584341060
raop_rtp audio: ntp = 1584340100553206, now = 1584340100281830, latency=-271376, rtp=1584340580
raop_rtp audio: ntp = 1584340100574975, now = 1584340100281855, latency=-293120, rtp=1584341540
Request not complete, waiting for more data...
Got AAC data of 10 bytes
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
Request not complete, waiting for more data...
httpd receiving on socket 15
conn_request
Handling request SET_PARAMETER with URL rtsp://10.0.10.21/0rtsp://10.0.10.21/0
Segmentation fault

**Comment by FD-** [comment]
Third-party clients are not supported. They often implement a very old version of the AirPlay mirroring protocol (pre-iOS 9).
