### ISSUE TITLE
docs: Clarify on which RPi models this works

### ISSUE THREAD

**Issue by lorenzleutgeb** [FD-/RPiPlay#78]
I'd like to know whether this software will (likely) work on a Raspberry 1 (Model B). Could you please also refer to older models like the one I have in `README.md`? Thanks.

**Comment by FD-** [comment]
I can only refer to the Pis I have actually tested on. However, you should be able to infer performance on any other Pi based on the information in the Readme: Given the Pi Zero is just about powerful enough for the task, the even slower Pi 1 B likely isn't up to the job. I'd expect it to work fine though if you don't need and disable the audio.
