### ISSUE TITLE
Firewall ports to allow screen mirroring?

### ISSUE THREAD

**Issue by roflmaooooo** [FD-/RPiPlay#91]
Works fine with my firewall turned off but I run a Pi4 with a restrictive firewall so I would like to know what ports should I open to enable screen mirroring. Might be helpful to many if you can include them in the documentation as well. Thanks for the great work btw!

**Comment by pimmler123** [comment]
Hi, Here are some Ports used by AirPlay:
https://nto.github.io/AirPlay.html#video
Maybe it worked if you open them.

**Comment by inferiorhumanorgans** [comment]
The way it's currently designed you'll need to open everything because RPiPlay lets the operating system pick random local ports.  If you were to hardcode the local ports you'd still need to open up everything outbound to the iDevice for audio synchronization to work.

**Comment by pallas** [comment]
Out of scope?
