### ISSUE TITLE
Headless or GUI Needed?

### ISSUE THREAD

**Issue by adrianmace** [FD-/RPiPlay#92]
Firstly I want to say wow this project looks great. Heaps better than spending $250 AUD on an Apple TV for the one non-smart tv in the house!

My Pi 3B+ is currently running Raspbian Lite which does not come with a desktop environment. Do I need to install any additional packages to get it working or should I begin with the full desktop edition?

**Comment by SashaRyder** [comment]
Im running headless, seems to work okay.

**Comment by FD-** [comment]
Yeah, I myself am mostly running this in headless Raspbian Lite.
