### ISSUE TITLE
Bluetooth Headphones

### ISSUE THREAD

**Issue by obaidsamadian** [FD-/RPiPlay#93]
I’ve connected a Bluetooth headphone to my raspberry pi. How can I set the rpiplay audio to the Bluetooth headphones?

**Comment by pallas** [comment]
No idea. Out of scope?

**Comment by FD-** [comment]
Since only the OpenMAX renderer (only supports HDMI and analog audio) works reliably (audio+video) on the Raspberry Pi, BT headphones are currently unsupported.

**Comment by ybm911** [comment]
This sounds sad
