### ISSUE TITLE
Overscan issues

### ISSUE THREAD

**Issue by kishu27** [FD-/RPiPlay#95]
Overscan settings as configured in `/boot/config.txt` is not being honored. 

My configured values are:

```
overscan_left=238
overscan_right=298
overscan_top=142
overscan_bottom=160
```

but apparently a large portion is still being cut-off (equal to the pixels specified). TV overscan settings are at the lowest.

**Comment by pallas** [comment]
RPiPlay is writing directly to the video buffer. My guess would be that you need to fix up your hardware configs to remove overscan/underscan, but I'm not an expert in how all that's configured. This seems out of scope to me, please reopen if you disagree.
