### ISSUE TITLE
FYI. Unix version of AirPlay server.

### ISSUE THREAD

**Issue by antimof** [FD-/RPiPlay#98]
Universal unix version of this project based on Gstreamer. Early prototype but fully working.
https://github.com/antimof/UxPlay

**Comment by FD-** [comment]
Fantastic! Are you planning to upstream the new renderers once you have them working? Does anything besides the renderers need modifications?

**Comment by antimof** [comment]
Sure I will do it

**Comment by FD-** [comment]
Cool! Let me know if you have any questions regarding implementation of the current renderers!

**Comment by antimof** [comment]
No. It works on any UX platform. The only concern is accelerated video sink. It even works on Raspberry pretty well with custom Gstreamer plugin gst-mmal for accelerated decode and screen output.

**Comment by FD-** [comment]
I'm particularly looking forward to seeing how the gstreamer renderers perform on the Pi Zero. Does gst-mmal support audio via USB audio cards or is audio handled by a different plugin anyway?

**Comment by antimof** [comment]
gst-mmal uses OpenMAX hdmi output. However, audio decoder is software only....

**Comment by FD-** [comment]
Audio decoding is software-only in the current renderers as well (AFAICT, the Pi doesn't have any hw audio decoders), so I'm hoping to see similar performance + possibility to use USB audio interfaces.

**Comment by pallas** [comment]
Should this work be wrapped back into RPiPlay? Definitely being able to build x86-64 will help my current debugging efforts. At which hash did you fork the code?

**Comment by antimof** [comment]
I think it was 5b2193c68e9b2c8f807dc56980b885cc12fd6043.

**Comment by pallas** [comment]
This was merged.
