### ISSUE TITLE
Same library for nodejs

### ISSUE THREAD

**Issue by ajouve** [FD-/RPiPlay#99]
Hi,

I am looking for a way to create an airplay server in nodejs.

Do you have any documentation about how this project works to do the same with nodejs ?

Thanks

**Comment by moda20** [comment]
it is not really advised to do it in nodeJS, you can try and control the current server in this repo using nodeJS though.

**Comment by ajouve** [comment]
Thanks I will try

Can this project be compiled on windows ?

Our nodejs app have to run on windows computer

**Comment by pallas** [comment]
Out of scope.
